### ISSUE TITLE
Ambassador Call for Application

### ISSUE THREAD

**Issue by peterayeniofficial** [peterayeniofficial/techclaritycoach#14]
A Social Media Design for TCC Ambassador

**Comment by Creadify** [comment]
![Image](https://github.com/peterayeniofficial/techclaritycoach/assets/136258671/474d2b3c-5dd0-4fe8-9e1b-c63e0f089110)

**Comment by ebuka1-anthony** [comment]
nice one

**Comment by ebuka1-anthony** [comment]
though i think you should open a PR for merge

**Comment by peterayeniofficial** [comment]
https://github.com/all-contributors please add @Creadify  for design, ideas

**Comment by peterayeniofficial** [comment]
@all-contributors please add @Creadify  for design, ideas

**Comment by peterayeniofficial** [comment]
@all-contributors please add @adeyemimichael  for content, eventOrganizing
